import './doc-layout'
import './doc-adapters'
import './doc-flow'
import './gst-returns'
import './asset-sale'
import './company-balance-sheet'
import './cards'
import './fx'
import { run } from './shim'
run()
