import './doc-layout'
import './doc-adapters'
import './doc-flow'
import './gst-returns'
import './asset-sale'
import './company-balance-sheet'
import './cards'
import './fx'
import './stocks'
import './forex-asset'
import './networth'
import './improvements'
import { run } from './shim'
run()
