export interface CurrencyMeta {
  code: string
  name: string
  symbol: string
  flag: string
}

// Comprehensive list of world currencies
export const CURRENCIES: CurrencyMeta[] = [
  { code: 'USD', name: 'US Dollar',              symbol: '$',       flag: '🇺🇸' },
  { code: 'EUR', name: 'Euro',                   symbol: '€',       flag: '🇪🇺' },
  { code: 'GBP', name: 'British Pound',          symbol: '£',       flag: '🇬🇧' },
  { code: 'JPY', name: 'Japanese Yen',           symbol: '¥',       flag: '🇯🇵' },
  { code: 'AUD', name: 'Australian Dollar',      symbol: 'A$',      flag: '🇦🇺' },
  { code: 'CAD', name: 'Canadian Dollar',        symbol: 'CA$',     flag: '🇨🇦' },
  { code: 'CHF', name: 'Swiss Franc',            symbol: 'Fr',      flag: '🇨🇭' },
  { code: 'CNY', name: 'Chinese Yuan',           symbol: '¥',       flag: '🇨🇳' },
  { code: 'HKD', name: 'Hong Kong Dollar',       symbol: 'HK$',     flag: '🇭🇰' },
  { code: 'SGD', name: 'Singapore Dollar',       symbol: 'S$',      flag: '🇸🇬' },
  { code: 'AED', name: 'UAE Dirham',             symbol: 'د.إ',     flag: '🇦🇪' },
  { code: 'SAR', name: 'Saudi Riyal',            symbol: '﷼',       flag: '🇸🇦' },
  { code: 'QAR', name: 'Qatari Riyal',           symbol: 'QR',      flag: '🇶🇦' },
  { code: 'KWD', name: 'Kuwaiti Dinar',          symbol: 'KD',      flag: '🇰🇼' },
  { code: 'BHD', name: 'Bahraini Dinar',         symbol: 'BD',      flag: '🇧🇭' },
  { code: 'OMR', name: 'Omani Rial',             symbol: 'RO',      flag: '🇴🇲' },
  { code: 'MYR', name: 'Malaysian Ringgit',      symbol: 'RM',      flag: '🇲🇾' },
  { code: 'THB', name: 'Thai Baht',              symbol: '฿',       flag: '🇹🇭' },
  { code: 'IDR', name: 'Indonesian Rupiah',      symbol: 'Rp',      flag: '🇮🇩' },
  { code: 'PHP', name: 'Philippine Peso',        symbol: '₱',       flag: '🇵🇭' },
  { code: 'VND', name: 'Vietnamese Dong',        symbol: '₫',       flag: '🇻🇳' },
  { code: 'KRW', name: 'South Korean Won',       symbol: '₩',       flag: '🇰🇷' },
  { code: 'TWD', name: 'Taiwan Dollar',          symbol: 'NT$',     flag: '🇹🇼' },
  { code: 'NZD', name: 'New Zealand Dollar',     symbol: 'NZ$',     flag: '🇳🇿' },
  { code: 'ZAR', name: 'South African Rand',     symbol: 'R',       flag: '🇿🇦' },
  { code: 'BRL', name: 'Brazilian Real',         symbol: 'R$',      flag: '🇧🇷' },
  { code: 'MXN', name: 'Mexican Peso',           symbol: '$',       flag: '🇲🇽' },
  { code: 'ARS', name: 'Argentine Peso',         symbol: '$',       flag: '🇦🇷' },
  { code: 'CLP', name: 'Chilean Peso',           symbol: '$',       flag: '🇨🇱' },
  { code: 'COP', name: 'Colombian Peso',         symbol: '$',       flag: '🇨🇴' },
  { code: 'PEN', name: 'Peruvian Sol',           symbol: 'S/',      flag: '🇵🇪' },
  { code: 'NOK', name: 'Norwegian Krone',        symbol: 'kr',      flag: '🇳🇴' },
  { code: 'SEK', name: 'Swedish Krona',          symbol: 'kr',      flag: '🇸🇪' },
  { code: 'DKK', name: 'Danish Krone',           symbol: 'kr',      flag: '🇩🇰' },
  { code: 'PLN', name: 'Polish Zloty',           symbol: 'zł',      flag: '🇵🇱' },
  { code: 'CZK', name: 'Czech Koruna',           symbol: 'Kč',      flag: '🇨🇿' },
  { code: 'HUF', name: 'Hungarian Forint',       symbol: 'Ft',      flag: '🇭🇺' },
  { code: 'RON', name: 'Romanian Leu',           symbol: 'lei',     flag: '🇷🇴' },
  { code: 'TRY', name: 'Turkish Lira',           symbol: '₺',       flag: '🇹🇷' },
  { code: 'RUB', name: 'Russian Ruble',          symbol: '₽',       flag: '🇷🇺' },
  { code: 'UAH', name: 'Ukrainian Hryvnia',      symbol: '₴',       flag: '🇺🇦' },
  { code: 'ILS', name: 'Israeli Shekel',         symbol: '₪',       flag: '🇮🇱' },
  { code: 'EGP', name: 'Egyptian Pound',         symbol: 'E£',      flag: '🇪🇬' },
  { code: 'NGN', name: 'Nigerian Naira',         symbol: '₦',       flag: '🇳🇬' },
  { code: 'KES', name: 'Kenyan Shilling',        symbol: 'KSh',     flag: '🇰🇪' },
  { code: 'GHS', name: 'Ghanaian Cedi',          symbol: 'GH₵',     flag: '🇬🇭' },
  { code: 'ETB', name: 'Ethiopian Birr',         symbol: 'Br',      flag: '🇪🇹' },
  { code: 'TZS', name: 'Tanzanian Shilling',     symbol: 'TSh',     flag: '🇹🇿' },
  { code: 'UGX', name: 'Ugandan Shilling',       symbol: 'USh',     flag: '🇺🇬' },
  { code: 'MAD', name: 'Moroccan Dirham',        symbol: 'MAD',     flag: '🇲🇦' },
  { code: 'DZD', name: 'Algerian Dinar',         symbol: 'DA',      flag: '🇩🇿' },
  { code: 'TND', name: 'Tunisian Dinar',         symbol: 'DT',      flag: '🇹🇳' },
  { code: 'LKR', name: 'Sri Lankan Rupee',       symbol: 'Rs',      flag: '🇱🇰' },
  { code: 'BDT', name: 'Bangladeshi Taka',       symbol: '৳',       flag: '🇧🇩' },
  { code: 'PKR', name: 'Pakistani Rupee',        symbol: '₨',       flag: '🇵🇰' },
  { code: 'NPR', name: 'Nepalese Rupee',         symbol: 'Rs',      flag: '🇳🇵' },
  { code: 'MMK', name: 'Myanmar Kyat',           symbol: 'K',       flag: '🇲🇲' },
  { code: 'KHR', name: 'Cambodian Riel',         symbol: '៛',       flag: '🇰🇭' },
  { code: 'LAK', name: 'Lao Kip',               symbol: '₭',       flag: '🇱🇦' },
  { code: 'MNT', name: 'Mongolian Tugrik',       symbol: '₮',       flag: '🇲🇳' },
  { code: 'AFN', name: 'Afghan Afghani',         symbol: '؋',       flag: '🇦🇫' },
  { code: 'IRR', name: 'Iranian Rial',           symbol: '﷼',       flag: '🇮🇷' },
  { code: 'IQD', name: 'Iraqi Dinar',            symbol: 'IQD',     flag: '🇮🇶' },
  { code: 'JOD', name: 'Jordanian Dinar',        symbol: 'JD',      flag: '🇯🇴' },
  { code: 'LBP', name: 'Lebanese Pound',         symbol: 'L£',      flag: '🇱🇧' },
  { code: 'SYP', name: 'Syrian Pound',           symbol: 'S£',      flag: '🇸🇾' },
  { code: 'YER', name: 'Yemeni Rial',            symbol: '﷼',       flag: '🇾🇪' },
  { code: 'GEL', name: 'Georgian Lari',          symbol: '₾',       flag: '🇬🇪' },
  { code: 'AMD', name: 'Armenian Dram',          symbol: '֏',       flag: '🇦🇲' },
  { code: 'AZN', name: 'Azerbaijani Manat',      symbol: '₼',       flag: '🇦🇿' },
  { code: 'KZT', name: 'Kazakhstani Tenge',      symbol: '₸',       flag: '🇰🇿' },
  { code: 'UZS', name: 'Uzbekistani Som',        symbol: 'soʻm',    flag: '🇺🇿' },
  { code: 'TWD', name: 'New Taiwan Dollar',      symbol: 'NT$',     flag: '🇹🇼' },
  { code: 'MOP', name: 'Macanese Pataca',        symbol: 'MOP$',    flag: '🇲🇴' },
  { code: 'BND', name: 'Brunei Dollar',          symbol: 'B$',      flag: '🇧🇳' },
  { code: 'FJD', name: 'Fijian Dollar',          symbol: 'FJ$',     flag: '🇫🇯' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K',       flag: '🇵🇬' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA',     flag: '🌍' },
  { code: 'XAF', name: 'Central African CFA',    symbol: 'FCFA',    flag: '🌍' },
  { code: 'DOP', name: 'Dominican Peso',         symbol: 'RD$',     flag: '🇩🇴' },
  { code: 'GTQ', name: 'Guatemalan Quetzal',     symbol: 'Q',       flag: '🇬🇹' },
  { code: 'HNL', name: 'Honduran Lempira',       symbol: 'L',       flag: '🇭🇳' },
  { code: 'CRC', name: 'Costa Rican Colón',      symbol: '₡',       flag: '🇨🇷' },
  { code: 'PAB', name: 'Panamanian Balboa',      symbol: 'B/.',     flag: '🇵🇦' },
  { code: 'BOB', name: 'Bolivian Boliviano',     symbol: 'Bs.',     flag: '🇧🇴' },
  { code: 'PYG', name: 'Paraguayan Guaraní',     symbol: '₲',       flag: '🇵🇾' },
  { code: 'UYU', name: 'Uruguayan Peso',         symbol: '$U',      flag: '🇺🇾' },
  { code: 'VES', name: 'Venezuelan Bolívar',     symbol: 'Bs.S',    flag: '🇻🇪' },
  { code: 'ISK', name: 'Icelandic Króna',        symbol: 'kr',      flag: '🇮🇸' },
  { code: 'HRK', name: 'Croatian Kuna',          symbol: 'kn',      flag: '🇭🇷' },
  { code: 'BGN', name: 'Bulgarian Lev',          symbol: 'лв',      flag: '🇧🇬' },
  { code: 'RSD', name: 'Serbian Dinar',          symbol: 'din',     flag: '🇷🇸' },
  { code: 'MKD', name: 'Macedonian Denar',       symbol: 'ден',     flag: '🇲🇰' },
  { code: 'ALL', name: 'Albanian Lek',           symbol: 'L',       flag: '🇦🇱' },
  { code: 'BAM', name: 'Bosnian Mark',           symbol: 'KM',      flag: '🇧🇦' },
  { code: 'MDL', name: 'Moldovan Leu',           symbol: 'L',       flag: '🇲🇩' },
  { code: 'BYN', name: 'Belarusian Ruble',       symbol: 'Br',      flag: '🇧🇾' },
]

export const CURRENCY_MAP: Record<string, CurrencyMeta> = Object.fromEntries(
  CURRENCIES.map(c => [c.code, c])
)

export const getCurrencyMeta = (code: string): CurrencyMeta =>
  CURRENCY_MAP[code] ?? { code, name: code, symbol: code, flag: '🌐' }
